manifest:
  projects:
    - name: nrf
      url: https://github.com/nrfconnect/sdk-nrf.git
      revision: refs/tags/v2.5.0
      import: true
    - name: sensirion_drivers
      path: modules/sensirion_drivers
      url: https://github.com/nobodyguy/sensirion_zephyr_drivers
      revision: main
  self:
    path: project