manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: ncs
      revision: v2.5.2
      import: true
    - name: sensirion_drivers
      path: modules/sensirion_drivers
      url: https://github.com/nobodyguy/sensirion_zephyr_drivers
      revision: main
  self:
    path: project